export ADBPG_ACCESS_KEY_ID=
export ADBPG_ACCESS_KEY_SECRET=
export ADBPG_REGION_ID=
export ADBPG_INSTANCE_ID=
export ADBPG_ACCOUNT=
export ADBPG_ACCOUNT_PASSWORD=
export ADBPG_NAMESPACE=
export ADBPG_NAMESPACE_PASSWORD=